---
- hosts: Rpis
  become: true
  vars: 
    version: "1.1.2"
    arch: armv7
  tasks:
    - include_vars: defaultusers.yml
    - name: Create a local Service User
      user:
        name: node_exporter
        shell: /bin/false
        createhome: no 
    - name: Apt full upgrade
      apt: 
        upgrade: full
        update_cache: yes
    - name: Download and unzip Node exporter
      ansible.builtin.unarchive:
        src: https://github.com/prometheus/node_exporter/releases/download/v{{version}}/node_exporter-{{version}}.linux-{{ arch }}.tar.gz
        dest: /var/tmp/
        remote_src: yes
    - name: Copy files to the install locations
      copy:
        src: /var/tmp/node_exporter-{{version}}.linux-{{arch}}/node_exporter
        dest: /usr/local/bin
        remote_src: yes
        owner: node_exporter
        group: node_exporter
        mode: a+x
    - name: Cleaning up the home directory source
      file:
        path: node_exporter-{{version}}.linux-{{arch}}/node_exporter
        state: absent
    - name: Cleaning up the home directory ZIP
      file:
        path: node_exporter-{{version}}.linux-{{arch}}/node_exporter
        state: absent
    - name: Download the service config file
      get_url:
        url: http://192.168.1.3:5769/node_exporter.service
        dest: /etc/systemd/system/
        force_basic_auth: yes
        url_username: SFS
        url_password: "{{SFS_pwd}}"
        group: node_exporter
        owner: node_exporter
    - name: Restart and enable the node exporter service
      service:
        name: node_exporter
        daemon_reload: yes
        state: started
        enabled: yes
    - name: Check the Service has started correctly
      uri:
        url: http://localhost:9100